# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Item Name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Unit Price')),
                ('image', models.ImageField(upload_to='', verbose_name='Item Image')),
                ('postback_code', models.CharField(editable=False, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=127)),
                ('customer_name', models.CharField(max_length=127)),
                ('address', models.TextField(default='NS')),
                ('phone', models.CharField(default='NS', max_length=127)),
                ('email', models.EmailField(default='NS', max_length=254)),
                ('bkash_transaction_no', models.CharField(default='NS', max_length=127)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('cart', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ItemCategory', verbose_name='Item Category'),
        ),
    ]
