# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='postback_code',
            field=models.CharField(default='dd', editable=False, max_length=127),
            preserve_default=False,
        ),
    ]
