# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Sub Category Name')),
                ('payload_code', models.CharField(editable=False, max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='payload_code',
            field=models.CharField(default='', editable=False, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='recipt_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.SubCategory', verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=127, verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ItemCategory', verbose_name='Parent Category'),
        ),
    ]
