# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_itemcategory_postback_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='postback_code',
            new_name='payload_code',
        ),
    ]
