# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171026_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Unit Price'),
        ),
    ]
