# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171026_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
