# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20171029_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='recipt_provided',
            field=models.BooleanField(default=False),
        ),
    ]
